// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywFoBka0aip0zT6xAtdkB88syB3ndmac',
    appId: '1:767252080955:web:b2a32b7533eb5c4501af1e',
    messagingSenderId: '767252080955',
    projectId: 'ispygameog',
    authDomain: 'ispygameog.firebaseapp.com',
    storageBucket: 'ispygameog.appspot.com',
    measurementId: 'G-KR61T2RXRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofpoTEcg_u4U1juJ4byWB125HJlYr8_U',
    appId: '1:767252080955:android:dc9dae942247ae1301af1e',
    messagingSenderId: '767252080955',
    projectId: 'ispygameog',
    storageBucket: 'ispygameog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4MIPWDlB0hDqyQ58Qndy5rbwhWy2Hd4',
    appId: '1:767252080955:ios:c47a1791123980a501af1e',
    messagingSenderId: '767252080955',
    projectId: 'ispygameog',
    storageBucket: 'ispygameog.appspot.com',
    iosClientId:
        '767252080955-1v5lbolpvt362g8gsbgrdol6ghg6b5mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.i_spy',
  );
}
